### ISSUE TITLE
Cannot save image asset via php

### ISSUE THREAD

**Issue by internetztube** [engram-design/ImageResizer#43]
### Steps to reproduce

1. Save an image via PHP into an asset object.

### Additional info

- Plugin version: 1af64ac61acdd4cb1f7accc7ed506213733361d7
- Craft version: Craft Pro 3.0.0-RC17.1

When I try to save an image into an asset object via a php plugin I get the following error:

```
Exception 'TypeError' with message 'Argument 1 passed to verbb\imageresizer\services\Service::getSettingForAssetSource() must be of the type integer, null given, called in /path/to/craft/vendor/verbb/image-resizer/src/ImageResizer.php on line 95'

in /path/to/craft/vendor/verbb/image-resizer/src/services/Service.php:23

Stack trace:
#0 /path/to/craft/vendor/verbb/image-resizer/src/ImageResizer.php(95): verbb\imageresizer\services\Service->getSettingForAssetSource(NULL, 'enabled')
#1 [internal function]: verbb\imageresizer\ImageResizer->beforeHandleAssetFile(Object(craft\events\AssetEvent))
#2 /path/to/craft/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(craft\events\AssetEvent))
#3 /path/to/craft/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\elements\\...', 'beforeHandleFil...', Object(craft\events\AssetEvent))
#4 /path/to/craft/vendor/craftcms/cms/src/elements/Asset.php(1185): yii\base\Component->trigger('beforeHandleFil...', Object(craft\events\AssetEvent))
#5 /path/to/craft/vendor/craftcms/cms/src/services/Elements.php(351): craft\elements\Asset->beforeSave(true)
#6 /path/to/PLUGIN/src/console/controllers/DefaultController.php(322): craft\services\Elements->saveElement(Object(craft\elements\Asset))
#7 /path/to/PLUGIN/src/console/controllers/DefaultController.php(165): atfredmansky\productsimporter\console\controllers\DefaultController->saveAsset('http://media.si...', Object(craft\elements\Asset), 't617-sigmund & ...')
#8 /path/to/PLUGIN/src/console/controllers/DefaultController.php(62): atfredmansky\productsimporter\console\controllers\DefaultController->fetchFeed()
#9 [internal function]: atfredmansky\productsimporter\console\controllers\DefaultController->actionIndex()
#10 /path/to/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /path/to/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /path/to/craft/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('index', Array)
#13 /path/to/craft/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('index', Array)
#14 /path/to/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('products-import...', Array)
#15 /path/to/craft/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('products-import...', Array)
#16 /path/to/craft/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /path/to/craft/craft(23): yii\base\Application->run()
#18 {main}
```

**Comment by engram-design** [comment]
Fixed in [2.0.3](https://github.com/verbb/image-resizer/releases/tag/2.0.3).
