### ISSUE TITLE
CLI batch resize

### ISSUE THREAD

**Issue by dgsiegel** [engram-design/ImageResizer#70]
### What are you trying to do?

I am currently trying to import a few hundred images via the CLI. It would be great to run batch resize via CLI, instead of having to log into the control panel.

### What's your proposed solution?

Add a CLI command :)

**Comment by romainpoirier** [comment]
I'm following up on this feature request.

Currently, the bulk resize functionality in the control panel (under `/image-resizer/settings`) lists all subfolders rather than volumes. In my setup, this results in hundreds of folders, causing the manual operation to be very extremely slowly to run.

It would be extremely useful if the bulk resize could be performed at the volume level, and even better using a CLI command. Do you have any updates or plans for addressing this issue in Craft CMS 5?

**Comment by engram-design** [comment]
Added the console command for the next release. To get this early, run

- `composer require verbb/image-resizer:"dev-craft-4 as 3.0.12"`.
- `composer require verbb/image-resizer:"dev-craft-5 as 4.0.2"`.

Supply either a `folder-id` or `volume` which supports multiple items with a comma:

```shell
./craft image-resizer/resize/bulk --volume=general,gallery
./craft image-resizer/resize/bulk --folder-id=1628,567
```

**Comment by romainpoirier** [comment]
Thank you for the addition! However, are you sure the console command was actually pushed?

After updating to `dev-craft-5 as 4.0.2`, I encountered the following error when trying to run:  

```sh
./craft image-resizer/resize/bulk --volume=images

Unknown command: image-resizer/resize/bulk
Caused by: Exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "image-resizer/resize/bulk".'

in /var/www/html/vendor/yiisoft/yii2/base/Module.php:561

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('image-resizer/r...', Array)
#1 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('image-resizer/r...', Array)
#2 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('image-resizer/r...', Array)
#3 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#4 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#5 /var/www/html/craft(13): yii\base\Application->run()
#6 {main}
Failed to execute command ./craft image-resizer/resize/bulk --volume=images: exit status 1
```

Additionally, I couldn't find this command in the plugin's source code. Could you confirm whether it is included?

**Comment by engram-design** [comment]
Whoops, you're right, simply forgot to push that merge. Let me know how that goes?

**Comment by romainpoirier** [comment]
Thanks, I can confirm that it works now!

**Comment by romainpoirier** [comment]
When do you plan to publicly release `dev-craft-5` so that we no longer have to use `dev-craft-5 as 4.0.2`?  Thanks!

**Comment by engram-design** [comment]
Sorry forgot to post an update here, released in [4.0.3](https://github.com/verbb/image-resizer/releases/tag/4.0.3)
